### ISSUE TITLE
Domain down!

### ISSUE THREAD

**Issue by Vild** [taddeimania/lctva#30]
The domain http://lctva.joel.io is currently down.

Is this intentional or what's up?

**Comment by taddeimania** [comment]
Sorry @Vild i brought it down because it was becoming a hassle dealing with the spot instances and I was throwing more money at it per month to host it than I felt people were getting out of it. Obviously you were likely 1 of my 2 active users on the site and i'm sorry for bringing it down.

I brought it back up and put it at https://lctva.xyz

Sorry for the hiatus :(

**Comment by Vild** [comment]
Thanks :)
